[package]
name = "kiv-lsp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kiv-lsp"
path = "src/main.rs"

[dependencies]
tower-lsp = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
env_logger = { workspace = true }

kivc = { workspace = true }
kivc-span = { workspace = true }
kivc-diagnostics = { workspace = true }
