[package]
name = "kiv-formatter"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kiv-fmt"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }

kivc = { workspace = true }
kivc-ast = { workspace = true }
kivc-span = { workspace = true }